[package]
name = "raytracer_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-hash = "1.1.0"
lodepng = "3.7.0"
rand = "0.8.5"
rand_chacha = "0.3.1"